name: Build with ESP-IDF v5.1

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install BTStack
      shell: bash
      run: cd external/btstack/port/esp32 && IDF_PATH=../../../../src/ ./integrate_btstack.py

    - name: Unijoysticle build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.1
        target: esp32
        path: 'src'
        command: 'idf.py -B build_plat_unijoysticle -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_unijoysticle" build'

    - name: AirLift build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.1
        target: esp32
        path: 'src'
        command: 'idf.py -B build_plat_airlift -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_airlift" build'

    - name: NINA build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.1
        target: esp32
        path: 'src'
        command: 'idf.py -B build_plat_nina -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_nina" build'

    - name: MightyMiggy build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.1
        target: esp32
        path: 'src'
        command: 'idf.py -B build_plat_mightymiggy -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_mightymiggy" build'

    - name: Custom build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v5.1
        target: esp32
        path: 'src'
        command: 'idf.py -B build_plat_custom -D SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.ci.plat_custom" build'

